### ISSUE TITLE
Errors on Linux Install

### ISSUE THREAD

**Issue by apadoopodo** [BlockchainWhispers/trailingstoploss3#3]
Thanks for this bot! Does this, should this work in Linux? I tried to follow the Mac OS instructions on a CENTOS 6 machine. Installed NodeJS then ran the install script, here is the result:

```
`user@server [/home/userdir/public_html/bbot/new2/trailingstoploss3]# ./install.sh

Installing StopTrailingLoss

> keccak@1.4.0 install /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/keccak
> node-gyp rebuild

make: Entering directory `/home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/8.11.1/include/node/v8.h:21,
                 from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/addon.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/addon.cc:1:
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:334: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:351: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:366: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:395: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/8.11.1/include/node/v8.h:397: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:402: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:442: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/8.11.1/include/node/v8.h:776: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:801: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:813: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:839: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h:1188: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h:1194: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/8.11.1/include/node/v8.h:1743: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:3213: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:3854: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:4123: error: function definition does not declare parameters
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from ../../nan/nan.h:68,
                 from ../src/addon.cc:2:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
cc1plus: warning: unrecognized command line option "-Wno-maybe-uninitialized"
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory `/home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/keccak
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-25T14_45_48_940Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> secp256k1@3.5.0 install /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.0 rebuild /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory `/home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
In file included from ../src/addon.cc:2:
../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /root/.node-gyp/8.11.1/include/node/v8.h:21,
                 from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/addon.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /root/.node-gyp/8.11.1/include/node/node.h:63,
                 from ../src/addon.cc:1:
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:334: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:351: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:366: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/root/.node-gyp/8.11.1/include/node/v8.h:395: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/root/.node-gyp/8.11.1/include/node/v8.h:397: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:402: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/8.11.1/include/node/v8.h:442: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/8.11.1/include/node/v8.h:776: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:801: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/8.11.1/include/node/v8.h:813: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:839: error: expected unqualified-id before ‘using’
/root/.node-gyp/8.11.1/include/node/v8.h:1188: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h:1194: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/root/.node-gyp/8.11.1/include/node/v8.h:1743: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:3213: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/8.11.1/include/node/v8.h:3854: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/8.11.1/include/node/v8.h: At global scope:
/root/.node-gyp/8.11.1/include/node/v8.h:4123: error: function definition does not declare parameters
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected unqualified-id before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘)’ before ‘&’ token
/root/.node-gyp/8.11.1/include/node/v8.h:4177: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from ../../nan/nan.h:68,
                 from ../src/addon.cc:2:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
cc1plus: warning: unrecognized command line option "-Wno-maybe-uninitialized"
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
make: Leaving directory `/home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/userdir/public_html/bbot/new2/trailingstoploss3/node_modules/secp256k1
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.5.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.5.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-25T14_45_50_078Z-debug.log
Secp256k1 bindings compilation fail. Pure JS implementation will be used.
added 185 packages from 162 contributors and audited 522 packages in 6.403s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details`
```

**Comment by trikunai** [comment]
i just wanna ask the same? any guideline or steps on how to run it in linux?
